language: node_js

node_js:
  - '0.10'

addons:
  firefox: '40.0.3'

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - $CI_ACTION

env:
  global:
    - TEST_SUITE=unit
  matrix:
    - CI_ACTION="npm run test-lint"
    - CI_ACTION="npm run test-unit"

